services:
    - docker

before_install:
    - docker build -t rogeriojma/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true rogeriojma/react-test npm test

after_success:
    - docker build -t rogeriojma/multi-client ./client
    - docker build -t rogeriojma/multi-nginx ./nginx
    - docker build -t rogeriojma/multi-server ./server
    - docker build -t rogeriojma/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
    # Take the images and push them to Docker Hub
    - docker push rogeriojma/multi-client
    - docker push rogeriojma/multi-nginx
    - docker push rogeriojma/multi-server
    - docker push rogeriojma/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket: "elasticbeanstalk-us-east-2-165086348688"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY